In [80]:
import pandas as pd
import numpy as np

In [81]:
sep = pd.read_csv("/kaggle/working/combined_reviews.tsv",delimiter='\t')

In [82]:
sep.shape

(1026, 2)

In [83]:
sep.loc[sep['Liked'].isna(), 'Liked'] = 2

In [84]:
sep['Liked'][sep['Liked'] == 1] =3
sep['Liked'][sep['Liked'] == 0] = 1

/tmp/ipykernel_33/2676711769.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sep['Liked'][sep['Liked'] == 1] =3
/tmp/ipykernel_33/2676711769.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sep['Liked'][sep['Liked'] == 1] =3
/tmp/ipykernel_33/2676711769.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sep['Liked'][sep['Liked'] == 0] = 1
/tmp/ipykernel_33/2676711769.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sep['Liked'][sep['Liked'] == 0] = 1

In [85]:
sep.head(10)

                                              Review  Liked
0                           Wow... Loved this place.    3.0
1                                 Crust is not good.    1.0
2          Not tasty and the texture was just nasty.    1.0
3  Stopped by during the late May bank holiday of...    3.0
4  The selection on the menu was great and so wer...    3.0
5     Now I am getting angry and I want my damn pho.    1.0
6              Honeslty it didn't taste THAT fresh.)    1.0
7  The potatoes were like rubber and you could te...    1.0
8                          The fries were great too.    3.0
9                                     A great touch.    3.0

In [86]:
sep['Liked'] = sep['Liked'].astype(int)

In [87]:
sep.head()

                                              Review  Liked
0                           Wow... Loved this place.      3
1                                 Crust is not good.      1
2          Not tasty and the texture was just nasty.      1
3  Stopped by during the late May bank holiday of...      3
4  The selection on the menu was great and so wer...      3

In [88]:
sep['Review'].to_csv('Review.txt',index=False,header=False)
sep['Liked'].to_csv('label.txt',index=False,header=False)